#!/bin/sh

NS_PREFIX=test-ns
ARGOCD_SERVERS_COUNT=5
NS_PER_SERVERS_COUNT=3
APP_PER_NS=2
APP_PREFIX=app
ARGOCD_SERVERS_PREFIX=argocd-server
TOTAL_NS=$(( $NS_PER_SERVERS_COUNT * $ARGOCD_SERVERS_COUNT))
